<a href="https://colab.research.google.com/github/naoya1110/DL_Lecture_202107/blob/main/Chapter03_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 03 Numpy Array

画像処理や深層学習で必須となるNumpy配列の扱いに慣れていきましょう。

まずはNumpyパッケージをインポートします。

In [1]:
import numpy as np

## Numpy配列（1D）のスライス

配列から一部の要素を取り出すことをスライスと言います。
まず，0から9まで１ずつ増加するNumpy配列`a`を作成します。

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

作成した配列aの2番目の要素，つまり2を取り出してみます。このとき配列の要素は0番目から始まることに注意しましょう。

In [3]:
a[2]

2

スライスに変数を使うこともできます。aのn番目の要素を取り出します。

In [4]:
n=8
a[n]

8

長い配列の場合，後ろから数えたほうが早い場合もあります。

次の例では，aの最後から2番目の要素（先頭から8番目の要素）を取り出します。最後から数える場合はマイナスをつけます。

In [5]:
a[-2]

8

スライス操作では，1つの要素だけではなく，複数の要素を取り出すことも可能です。

次の例ではaの3番目から7番目までの要素を取り出します。このとき``` a[開始：終了］ ``` の終了部分には8を入力します。これは，終了条件が『n番目の要素未満で終了』を表しているためです。

In [6]:
a[3:8]

array([3, 4, 5, 6, 7])

## Numpy配列の変形

まず，0から14まで１ずつ増加する一次元の配列bを作成します。

In [7]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

作成した一次元配列bを3行x5列の二次元配列cに変形してみましょう。配列の変形には```元の配列名.reshape(行，列)```を使用します。

In [8]:
c = b.reshape(3, 5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

今度は一次元配列bを5行x3列の二次元配列dに変形します。

In [9]:
d = b.reshape(5, -1)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

もちろん，配列Dを元の１次元配列に変形することも可能です。この場合は（）の中に要素数を記述します。

In [10]:
e = d.reshape(15)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

配列の要素数がわからない場合，（）内に-1を記述すると適切に変換可能です。

In [11]:
e2 = d.reshape(-1)
e2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Numpy配列（2D）のスライス

２次元配列でもスライス操作が行えます。

まずは10行x10列の配列fを作成します。arange().reshape()は繋げて１行に書くことができます。

In [12]:
f = np.arange(100).reshape(10,10)
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

二次元配列fの0行目（一次元配列）を取り出します。列はすべて取り出すので：を入力します。

In [13]:
f[0, :]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

二次元配列fの2列目（一次元配列）を取り出します。

In [14]:
f[:, 2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

二次元配列fの一部（二次元配列）を取り出します。
次の例では，１行目から４行目未満（１から３行目），３列目から９列目未満（３から８列目）をとりだしています。

In [15]:
f[1:4,3:9]

array([[13, 14, 15, 16, 17, 18],
       [23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38]])

## Numpy配列に対する比較演算

In [16]:
g = np.arange(10)
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

配列gに対して比較演算をすると，各要素に対する演算結果の配列が出力されます。

In [17]:
g > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

これを用いれば配列gから条件を満たす要素のみをまとめた配列を生成することができます。

In [18]:
# gのうち要素が5より大きいものをまとめた配列
g[g>5]

array([6, 7, 8, 9])

In [19]:
# gのうち偶数のみをまとめた配列
g[g%2==0]

array([0, 2, 4, 6, 8])

## その他のNumpy配列

要素が全て0の配列

In [20]:
np.zeros(3)

array([0., 0., 0.])

要素が全て1の配列

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

乱数の配列

In [22]:
np.random.rand(5)

array([0.13426576, 0.91213274, 0.23330128, 0.35652733, 0.22518286])

単位行列

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])